server:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: job-client-1
  main:
    allow-bean-definition-overriding: true # SpringBoot 2.1需要设置


logging:
  level:
    com.pro: INFO

# debug: true
