server:
  port: 8090
  servlet:
    context-path: /openJob

spring:
  profiles:
    active: dev
  application:
    name: job-admin
  main:
    allow-bean-definition-overriding: true # SpringBoot 2.1需要设置

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  type-enums-package: com.saucesubfresh.job.admin.enums*;com.saucesubfresh.job.common.enums*
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    com.saucesubfresh: INFO

report-cron-express: "0 59 23 * * ? *"

com:
  saucesubfresh:
    rpc:
      server:
        client-name: job-client-services
    captcha:
      image:
        length: 4 #图形验证码的位数为6，将覆盖默认配置中的4
        width: 200 #图形验证码的宽度为100，将覆盖默认配置中的67，但由于请求中设置的宽度为200，所以真正的宽度将为200
        height: 60
      scan:
        width: 300 #二维码宽度
        height: 300 #二维码高度
        margin: 1 #二维码外边距，0到4
    security:
      ignore-paths:
        - "/captcha/**"
        - "/login/**"
    alarm:
      # 这里的 {xxxxxx} 替换成你的钉钉机器人的 secret
      secret: xxxxxx
      # 这里 {xxxxxxxx} 替换成你的钉钉机器人的 access_token
      webhook: https://oapi.dingtalk.com/robot/send?access_token=xxxxxxxx